version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./db:/var/lib/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: web_app:latest
    container_name: 'web_app'
    network_mode: host
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
      - "2222:22"
